CREATE TABLE "mytable" (
  "-- Thay your-admin-email@example.com bằng email admin thật của bạn trước khi chạy." text
);

INSERT INTO "mytable" ("-- Thay your-admin-email@example.com bằng email admin thật của bạn trước khi chạy.")
VALUES
('create extension if not exists pgcrypto;'),
('create table if not exists public.videos ('),
('id uuid primary key default gen_random_uuid()'),
('title text not null'),
('category text'),
('description text'),
('video_url text not null'),
('storage_path text not null'),
('is_published boolean not null default true'),
('created_by text'),
('created_at timestamptz not null default now()'),
(');'),
('alter table public.videos enable row level security;'),
('insert into storage.buckets (id'),
('values (''price-videos'''),
('on conflict (id) do nothing;'),
('create policy "Public can read published videos"'),
('on public.videos'),
('for select'),
('using (is_published = true);'),
('create policy "Admin can insert videos"'),
('on public.videos'),
('for insert'),
('to authenticated'),
('with check (auth.email() = ''buiducbao89@gmail.com'');'),
('create policy "Admin can update videos"'),
('on public.videos'),
('for update'),
('to authenticated'),
('using (auth.email() = ''buiducbao89@gmail.com'')'),
('with check (auth.email() = ''buiducbao89@gmail.com'');'),
('create policy "Admin can delete videos"'),
('on public.videos'),
('for delete'),
('to authenticated'),
('using (auth.email() = ''buiducbao89@gmail.com'');'),
('create policy "Public can view price videos in storage"'),
('on storage.objects'),
('for select'),
('using (bucket_id = ''price-videos'');'),
('create policy "Admin can upload price videos"'),
('on storage.objects'),
('for insert'),
('to authenticated'),
('with check ('),
('bucket_id = ''price-videos'''),
('and auth.email() = ''buiducbao89@gmail.com'''),
(');'),
('create policy "Admin can update price videos"'),
('on storage.objects'),
('for update'),
('to authenticated'),
('using ('),
('bucket_id = ''price-videos'''),
('and auth.email() = ''buiducbao89@gmail.com'''),
(')'),
('with check ('),
('bucket_id = ''price-videos'''),
('and auth.email() = ''buiducbao89@gmail.com'''),
(');'),
('create policy "Admin can delete price videos"'),
('on storage.objects'),
('for delete'),
('to authenticated'),
('using ('),
('bucket_id = ''price-videos'''),
('and auth.email() = ''buiducbao89@gmail.com'''),
(');');
